In [25]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd

In [26]:
X , y = make_classification(n_samples=100, n_features=4, n_informative=1, n_redundant=0, n_classes=2 , n_clusters_per_class=1, n_repeated=0, random_state=42)

In [27]:
df = pd.DataFrame(X , columns=[f"Feature{i + 1}" for i in range(X.shape[1])])
df["target"] = y

In [28]:
df.head()

,Feature1,Feature2,Feature3,Feature4,target
0,0.628346,0.543199,0.624120,0.791663,1
1,-0.599375,1.130380,-1.594428,1.237816,1
2,-1.320233,0.835421,0.491919,-0.898415,1
3,-0.846794,-0.900788,-0.072829,0.473238,0
4,0.515035,-1.135866,-0.937825,-1.377669,0


In [29]:
X.shape

(100, 4)

In [62]:
class PerceptronTrick:
    def __init__(self, epochs = 100, learning_rate = 0.01):
        self.coeffs = None
        self.intercept = None
        self.epochs = epochs
        self.lr = learning_rate

    def fit(self,X,y):
        self.intercept = 0
        self.coeffs = np.zeros(X.shape[1])
        for i in range(self.epochs):
            # select an random point
            row = np.random.randint(0 , X.shape[0])
            y_cap = step(np.dot(self.coeffs , X[row]) + self.intercept)
            self.coeffs = self.coeffs + self.lr * (y[row] - y_cap) * X[row]
            self.intercept = self.intercept + self.lr * (y[row] - y_cap) 
    def predict(self,X):
        y_prediction = np.dot(X , self.coeffs) + self.intercept
        y_pred = []
        for i in range(X.shape[0]):
            if y_prediction[i] >= 0 :
                y_pred.append(1)
            else:
                y_pred.append(0)
        return y_pred
def step(value):
        return 1 if value >= 0 else 0
    

In [63]:
np.zeros(X.shape[1])

array([0., 0., 0., 0.])

In [64]:
X.shape

(100, 4)

In [65]:
np.random.randint(0 , X.shape[0])

71

In [58]:
X[65]

array([-0.11453985,  0.99715802,  1.35387237, -1.71313453])

In [59]:
X[65].shape

(4,)

In [36]:
(4 , ) x (4,) => 1 , 4 * 4 , 1 = 1 , 1

SyntaxError: invalid syntax (3062541418.py, line 1)

In [37]:
 np.dot([1,1,1,1], X[65]) + 1

np.float64(1.5233560204970447)

In [38]:
2 + 0.01 * (1 - 0) * X[65]

array([1.9988546 , 2.00997158, 2.01353872, 1.98286865])

In [66]:
pt = PerceptronTrick()

In [67]:
pt.fit(X,y)

In [68]:
np.array(pt.predict(X)).shape

(100,)

In [69]:
from sklearn.metrics import r2_score

In [70]:
r2_score(y , np.array(pt.predict(X)).reshape(100))

1.0

In [71]:
y

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0])