In [3]:
from sklearn.datasets import load_diabetes

In [14]:
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [5]:
X,y = load_diabetes(return_X_y=True)

In [6]:
X.shape

(442, 10)

In [17]:
y.shape

(442,)

In [18]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(X, columns = [f"Feature_{i+1}" for i in range(X.shape[1])])

In [23]:
df["Target"] = y

In [24]:
df.head()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [26]:
X_train,X_test, y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=13)

## Using SGD Regressor of SKLearn

In [28]:
gd = SGDRegressor(penalty=None)
gd.fit(X_train,y_train)

/home/subhamoy/miniforge3/envs/tf_gpu/lib/python3.12/site-packages/sklearn/linear_model/_stochastic_gradient.py:1579: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


,loss,'squared_error'
,penalty,None
,alpha,0.0001
,l1_ratio,0.15
,fit_intercept,True
,max_iter,1000
,tol,0.001
,shuffle,True
,verbose,0
,epsilon,0.1
,random_state,None


In [29]:
y_pred_sklearn = gd.predict(X_test)

In [207]:
print(r2_score(y_test,y_pred_sklearn))
print(gd.coef_)
print(gd.intercept_)

0.3635859996454024
[  42.85847476  -33.87775736  276.35744242  185.43635648   45.20554401
   20.54254887 -141.80208259  134.95564267  223.32645402  143.92536127]
[150.2315302]


## Our Class

In [209]:
import matplotlib.pyplot as plt

In [178]:
# intercept = Wo
class BatchGradientDescent:
    def __init__(self, epochs = 100, learning_rate = 0.01):
        self.intercept = None
        self.weights = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit (self, X_train, y_train):
        print(X_train.shape[1])
        self.weights = np.ones(X_train.shape[1])
        self.intercept = 0
        print("Initital Weight Shape" , self.weights)
        for i in range(self.epochs):
            y_cap = self.intercept + np.dot(X_train , self.weights)
            intercept_der = -2 * np.mean(y_train - y_cap)
            self.intercept = self.intercept - self.lr * intercept_der
            weights_der = -2 * np.dot((y_train - y_cap) , X_train) / X_train.shape[0]
            print("weights_der: ", weights_der.shape)
            self.weights = self.weights - self.lr * weights_der
            print(f"{i} Weight Shape: " , self.weights.shape)
            print(f"{i} Weight : " , self.weights)
    def predict(self, X_test):
        return self.intercept + np.dot(X_test , self.weights)

In [179]:
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [180]:
np.ones(X_train.shape[1]).shape

(10,)

In [181]:
np.dot(X , np.ones(X_train.shape[1]))

array([ 4.95486093e-02, -2.77554722e-01,  3.69486749e-02, -1.33177387e-01,
       -1.07318583e-01, -5.18393379e-01, -2.62837913e-01,  3.86273006e-01,
        7.13573612e-02, -1.30129042e-01, -5.98101434e-01, -4.87329767e-02,
       -1.48185599e-01,  6.16247009e-02, -8.51720569e-02,  3.19140705e-01,
        1.57380392e-01,  2.94364608e-01, -2.53868917e-01, -2.10158462e-01,
       -3.18147476e-01, -2.33384528e-01, -2.29717691e-01,  4.55032929e-01,
       -2.34701856e-01, -1.18888515e-01, -5.38999041e-01, -1.38638861e-01,
       -2.67207753e-01,  1.24185267e-01, -1.50152087e-01, -4.03884100e-01,
        2.06406733e-01, -1.73465587e-01, -4.14073501e-01,  1.85321833e-01,
        5.01558702e-02, -1.65430865e-01,  5.26187973e-01,  3.02459345e-03,
        3.13692709e-01, -5.51627960e-01, -1.94379695e-01, -3.57936221e-02,
        1.69677258e-01, -1.35447447e-02, -3.71527250e-01, -5.78073618e-01,
        1.65578763e-02,  3.13780528e-02, -1.40629806e-01,  2.96285776e-02,
       -3.57201315e-02,  

In [182]:
np.dot(X , np.ones(X_train.shape[1])).shape

(442,)

In [183]:
X.shape

(442, 10)

In [184]:
np.ones(X_train.shape[1]).shape

(10,)

In [185]:
y.shape

(442,)

In [200]:
ourBatchGD = BatchGradientDescent(learning_rate=0.09, epochs=1000)

In [201]:
ourBatchGD.fit(X_train,y_train)

10
Initital Weight Shape [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
weights_der:  (10,)
0 Weight Shape:  (10,)
0 Weight :  [1.09519976 1.00665789 1.45592513 1.29908736 1.26304191 1.24182574
 0.7447377  1.34797921 1.41885755 1.32067542]
weights_der:  (10,)
1 Weight Shape:  (10,)
1 Weight :  [1.19436483 1.01619106 1.90398963 1.5981287  1.50681685 1.46341249
 0.49093585 1.6849148  1.82888626 1.632986  ]
weights_der:  (10,)
2 Weight Shape:  (10,)
2 Weight :  [1.29673644 1.02804807 2.34552685 1.89706473 1.73472399 1.66833574
 0.23839438 2.01270261 2.23158618 1.93835967]
weights_der:  (10,)
3 Weight Shape:  (10,)
3 Weight :  [ 1.40169247  1.04177679  2.78163027  2.1958469   1.94955074  1.85952747
 -0.01305087  2.33289735  2.62818751  2.23796743]
weights_der:  (10,)
4 Weight Shape:  (10,)
4 Weight :  [ 1.50872287  1.05700658  3.21319663  2.49443552  2.1535829   2.039392
 -0.2635346   2.64677403  3.01969913  2.53276962]
weights_der:  (10,)
5 Weight Shape:  (10,)
5 Weight :  [ 1.6174095   1.07343354  3.64

In [202]:
X_train.shape[1]

10

In [203]:
ourBatchGD.intercept

np.float64(150.3064985734584)

In [204]:
ourBatchGD.weights

array([  43.51928336,  -29.29975662,  264.77461862,  178.66824766,
         46.48074014,   23.3567786 , -135.98007347,  132.6542    ,
        215.39385617,  140.35162049])

In [205]:
y_pred = ourBatchGD.predict(X_test)

In [206]:
r2_score(y_test, y_pred)

0.3601329814002866