In [1]:
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import cross_val_score

In [3]:
X , y = make_regression(n_samples=100, n_features=6, n_informative=6, n_targets=1, noise = 20, random_state=15)

In [4]:
import pandas as pd

In [6]:
df_X = pd.DataFrame(X, columns = [f"Feature_{i+1}" for i in range(X.shape[1])])

In [8]:
df_Y = pd.DataFrame(y , columns = ["Target"])

In [9]:
df = pd.concat([df_X, df_Y], axis = 1)

In [13]:
df.head()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Target
0,-0.106834,0.517177,0.580846,-2.821792,-0.704303,0.129972,-215.454437
1,0.511137,-0.371729,-1.308796,0.059701,0.284830,-1.011787,-101.268005
2,0.170620,0.009562,0.085592,0.805421,0.154418,1.164216,123.102027
3,-1.213008,-1.697875,-0.631793,0.286367,1.548128,-0.563130,-153.373819
4,-1.740547,-0.261622,-0.197070,0.276504,-0.136303,0.776081,-48.380999


In [12]:
X.shape

(100, 6)

In [53]:
class OurGradientDescent: 
    def __init__(self, learning_rate = 0.01 , epochs = 100):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.intercept = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        # Initialization
        self.intercept = 0
        self.weights = np.zeros(n_features)
        print(self.weights.shape)

        # Gradient Descent
        for i in range(self.epochs):
            y_cap = self.intercept + np.dot(X, self.weights)
            i_der = (-2 / n_samples) * np.sum(y - y_cap)
            self.intercept = self.intercept - self.lr * i_der
            w_der = (-2 / n_samples) * np.dot(X.T , (y - y_cap) )
            self.weights = self.weights - self.lr * w_der

    def predict(self,X):
        return np.dot(X, self.weights) + self.intercept

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
X.shape

(100, 6)

In [16]:
X.T.shape

(6, 100)

In [54]:
gd = OurGradientDescent()

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [56]:
gd.fit(X_train,y_train)

(6,)


In [26]:
y_pred = gd.predict(X_test)

In [27]:
from sklearn.metrics import r2_score

In [28]:
r2_score(y_test, y_pred)

0.9400151002405658

In [30]:
gd.intercept

np.float64(-0.9313682675369)

In [31]:
gd.weights

array([36.89744629, 86.0036845 , 26.58669588, 62.29971933, 29.7990642 ,
       39.46460009])

 # Gradient Descent from sklearn


In [33]:
from sklearn.linear_model import SGDRegressor

In [49]:
sgdregressor = SGDRegressor(penalty=None, max_iter=100 , learning_rate="constant", tol = 1e-3, eta0=0.01)
sgdregressor.fit(X_train, y_train)
pred = sgdregressor.predict(X_test)

In [50]:
from sklearn.metrics import r2_score
r2_score(y_test, pred)

0.9747617802923688

In [51]:
sgdregressor.intercept_

array([0.6306818])

In [52]:
sgdregressor.coef_

array([45.96413569, 99.77369481, 26.04304876, 73.7499826 , 41.64048793,
       41.59866957])